version: 2

sources:
  - name: raw_data
    description: Raw market data from Databento
    tables:
      - name: ohlcv_1m
        description: 1-minute OHLCV data for NQ futures
      - name: symbology
        description: Symbol to instrument mapping

models:  
  - name: int_technical_indicators
    description: Technical indicators and momentum calculations
    columns:
      - name: sma_20
        description: 20-period simple moving average
      - name: trend_direction
        description: Overall trend classification
        tests:
          - accepted_values:
              values: ['UPTREND', 'DOWNTREND', 'SIDEWAYS']
  
  - name: daily_market_summary
    description: Daily aggregated market data
    columns:
      - name: trade_date
        description: Trading date
        tests:
          - not_null
          - unique
      - name: daily_volume
        description: Total daily volume
        tests:
          - not_null
  
  - name: nq_trading_signals
    description: Algorithm-generated trading signals
    columns:
      - name: algorithm_signal
        description: Final trading signal
        tests:
          - accepted_values:
              values: ['STRONG_BUY', 'BUY', 'HOLD', 'SELL', 'STRONG_SELL']
      - name: event_timestamp
        description: Signal timestamp
        tests:
          - not_null
